version: '3.2'

volumes:
  esdata-dev:

services:
  elasticsearch-dev:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: elasticsearch-dev
    container_name: elasticsearch-dev
    volumes:
    - type: bind
      source: esdata-dev
      target: /usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
  django-blog-dev:
    depends_on:
      - elasticsearch-dev
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: django-blog-dev
    container_name: django-blog-dev
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
    - "8000:8000"
    command: /start.sh
