version: '3.2'

volumes:
  static:
  database:
  esdata-prod:

services:
  elasticsearch-prod:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: elasticsearch-prod
    container_name: elasticsearch-prod
    volumes:
      - type: bind
        source: esdata-prod
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536

  django-blog-prod:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    depends_on:
      - elasticsearch-prod
    image: django-blog-prod
    container_name: django-blog-prod
    working_dir: /app
    volumes:
      - type: bind
        source: database
        target: /app/database
      - type: bind
        source: static
        target: /app/static
    #  - database: "/app/database"
    #  - static: /app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    depends_on:
      - django-blog-prod
    image: nginx
    container_name: nginx
    volumes:
      - type: bind
        source: static
        target: /apps/django-blog/static
 #     - static: /apps/django-blog/static
    ports:
      - "80:80"
      - "443:443"

